param(
  [string]$Root = ".",
  [string]$TargetRoot = ".",
  [switch]$WriteReport,
  [switch]$WriteAdapterDraft
)

$ErrorActionPreference = "Stop"

function Add-Item {
  param(
    [System.Collections.Generic.List[object]]$List,
    [string]$Area,
    [string]$Status,
    [string]$Message
  )

  $List.Add([pscustomobject]@{
    Area = $Area
    Status = $Status
    Message = $Message
  }) | Out-Null
}

function Test-PlaceholderProjectConfig {
  param([string]$ProjectConfigPath)

  if (-not (Test-Path -LiteralPath $ProjectConfigPath)) {
    return $true
  }

  $text = Get-Content -LiteralPath $ProjectConfigPath -Raw
  return ($text -match 'id:\s*""' -or $text -match 'name:\s*""' -or $text -match 'languages:\s*\[\]')
}

function Get-DetectedStack {
  param([string]$TargetRootPath)

  $items = New-Object System.Collections.Generic.List[string]

  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "package.json")) { $items.Add("node-js") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "pnpm-lock.yaml")) { $items.Add("pnpm") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "yarn.lock")) { $items.Add("yarn") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "package-lock.json")) { $items.Add("npm") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "pyproject.toml")) { $items.Add("python") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "requirements.txt")) { $items.Add("python-requirements") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "pubspec.yaml")) { $items.Add("flutter-dart") | Out-Null }
  if (@(Get-ChildItem -LiteralPath $TargetRootPath -Filter "*.csproj" -File -ErrorAction SilentlyContinue).Count -gt 0) { $items.Add("dotnet") | Out-Null }
  if (Test-Path -LiteralPath (Join-Path $TargetRootPath "go.mod")) { $items.Add("go") | Out-Null }

  if ($items.Count -eq 0) {
    $items.Add("unknown") | Out-Null
  }

  return @($items)
}

function Write-AdapterDraft {
  param(
    [string]$Path,
    [string]$TargetRootPath,
    [string[]]$DetectedStack
  )

  $projectName = Split-Path -Leaf $TargetRootPath
  $languages = if ($DetectedStack -contains "python" -or $DetectedStack -contains "python-requirements") { '["python"]' } elseif ($DetectedStack -contains "flutter-dart") { '["dart"]' } elseif ($DetectedStack -contains "dotnet") { '["csharp"]' } elseif ($DetectedStack -contains "go") { '["go"]' } elseif ($DetectedStack -contains "node-js") { '["javascript", "typescript"]' } else { "[]" }
  $packageManager = if ($DetectedStack -contains "pnpm") { "pnpm" } elseif ($DetectedStack -contains "yarn") { "yarn" } elseif ($DetectedStack -contains "npm") { "npm" } elseif ($DetectedStack -contains "flutter-dart") { "flutter" } elseif ($DetectedStack -contains "python") { "python" } elseif ($DetectedStack -contains "dotnet") { "dotnet" } elseif ($DetectedStack -contains "go") { "go" } else { "" }

  $content = @"
# Project adapter draft generated by HEPHAESTUS.
# Review before copying into .agents/config/project.yaml.

project:
  id: "$($projectName.ToLowerInvariant() -replace '[^a-z0-9_-]', '-')"
  name: "$projectName"
  profile: ""
  root: "."
  description: ""
  maturity: "bootstrap-draft"

stack:
  languages: $languages
  frameworks: []
  runtime: []
  databases: []
  package_manager: "$packageManager"
  platforms: []

commands:
  install:
    command: ""
    allowed: false
  test:
    command: ""
    allowed: false
  lint:
    command: ""
    allowed: false
  build:
    command: ""
    allowed: false
  format:
    command: ""
    allowed: false
  dev:
    command: ""
    allowed: false

paths:
  source: []
  tests: []
  docs: []
  generated: []
  protected:
    - ".git/"
    - ".agents/"
    - ".env"
    - ".env.*"
    - "secrets.*"
    - "credentials.*"

execution:
  mode: "analysis_only"
  require_plan_before_changes: true
  require_approval_before_apply: true
  backup_before_mutation: true
  allow_destructive_commands: false

quality_gates:
  required: []
  optional: []
  manual:
    - "Confirm adapter commands before enabling allowed=true."
"@

  Set-Content -LiteralPath $Path -Value $content
}

$resolvedRoot = (Resolve-Path $Root).Path
$targetRootPath = if (Test-Path -LiteralPath $TargetRoot) { (Resolve-Path $TargetRoot).Path } else { [System.IO.Path]::GetFullPath($TargetRoot) }
$agentsRoot = Join-Path $resolvedRoot ".agents"
$projectConfigPath = Join-Path $targetRootPath ".agents/config/project.yaml"
$reportDir = Join-Path $agentsRoot "reports/adapters"
$reportPath = Join-Path $reportDir "project-bootstrap-latest.md"
$draftPath = Join-Path $reportDir "project-adapter-draft.yaml"
$items = New-Object System.Collections.Generic.List[object]

if (Test-Path -LiteralPath $targetRootPath -PathType Container) {
  Add-Item $items "target" "PASS" "Target root exists: $targetRootPath"
} else {
  Add-Item $items "target" "WARN" "Target root does not exist yet: $targetRootPath"
}

$detectedStack = Get-DetectedStack $targetRootPath
Add-Item $items "stack" "INFO" "Detected stack: $($detectedStack -join ', ')"

if (Test-Path -LiteralPath $projectConfigPath) {
  if (Test-PlaceholderProjectConfig $projectConfigPath) {
    Add-Item $items "adapter" "WARN" "Project adapter exists but still looks like a template"
  } else {
    Add-Item $items "adapter" "PASS" "Project adapter has project-specific values"
  }
} else {
  Add-Item $items "adapter" "WARN" "Project adapter not found in target"
}

Add-Item $items "discovery" "INFO" "Use Project Discovery for product story, use cases, business rules, costs, legal/IP, and implementation readiness"
Add-Item $items "next-action" "INFO" "Mature requirements first, then confirm adapter commands before controlled execution"

if ($WriteReport -or $WriteAdapterDraft) {
  New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

if ($WriteAdapterDraft) {
  Write-AdapterDraft -Path $draftPath -TargetRootPath $targetRootPath -DetectedStack $detectedStack
  Add-Item $items "adapter-draft" "PASS" ".agents/reports/adapters/project-adapter-draft.yaml"
}

if ($WriteReport) {
  $timestamp = (Get-Date).ToString("o")
  $status = if (@($items | Where-Object { $_.Status -eq "WARN" }).Count -gt 0) { "partial" } else { "ready" }
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# HEPHAESTUS Project Bootstrap Report") | Out-Null
  $lines.Add("") | Out-Null
  $lines.Add("---") | Out-Null
  $lines.Add('log_type: "project-bootstrap"') | Out-Null
  $lines.Add("timestamp: `"$timestamp`"") | Out-Null
  $lines.Add("status: `"$status`"") | Out-Null
  $lines.Add('event: "project_bootstrap.completed"') | Out-Null
  $lines.Add('framework_version: "8.7.0"') | Out-Null
  $lines.Add("---") | Out-Null
  $lines.Add("") | Out-Null
  $lines.Add("## Target") | Out-Null
  $lines.Add("") | Out-Null
  $lines.Add("- Root: $targetRootPath") | Out-Null
  $lines.Add("- Detected stack: $($detectedStack -join ', ')") | Out-Null
  $lines.Add("") | Out-Null
  $lines.Add("## Bootstrap Checks") | Out-Null
  $lines.Add("") | Out-Null
  foreach ($item in $items) {
    $lines.Add("- $($item.Status) $($item.Area): $($item.Message)") | Out-Null
  }
  $lines.Add("") | Out-Null
  $lines.Add("## Discovery Bridge") | Out-Null
  $lines.Add("") | Out-Null
  $lines.Add("- Project Discovery remains the source for story, use cases, users, rules, costs, legal/IP, and readiness.") | Out-Null
  $lines.Add("- Real Project Adapter remains the source for commands, paths, protected files, and quality gates.") | Out-Null
  $lines | Set-Content -LiteralPath $reportPath
}

$items | Format-Table -AutoSize
$summary = $items | Group-Object Status | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }
Write-Host ""
Write-Host "Project bootstrap summary: $($summary -join ', ')"

exit 0
